# -*- coding: utf-8 -*-
"""Amigo_Fiel_PET.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qgdybRfSGGIeZRtKOK6HPYjEgo9Vn2bT
"""

#Mensagem de boas vindas
print("Seja Bem Vindo(a) Ao Pet-Shop : Amigo Fiel!" )

produtos = ["Ração - R$50.00", "Areia - R$20.00", "Coleira - R$10.00"]
servicos = ["Banho - R$70.00", "Tosa - R$50.00"]
carrinho = []
total_item= []
totalT= 0
precos_produtos = (50, 20, 10,)
precos_servicos = (70, 50,)
compra=0


#Acesso a Loja
while True:
  inicio = input('''
    Deseja:
    [A] Acessar a loja:
    [F] Sair da loja: ''').upper()

  if inicio == "A":
    while True:
      menustr = input('''
        [1] Listar produtos:
        [2] Listar serviços:
        [3] Adicionar:
        [4] Remover produto:
        [5] Visualizar carrinho:
        [6] Finalizar compra:
        [7] Voltar
        ''')
           
      if menustr.isnumeric():
        menu=int(menustr)
      
        if menu == 1:
          print("-" * 25)
          for i in produtos:
            print(i)
          print("-" * 25)
        elif menu == 2:
          print("-" * 25)
          for i in servicos:
            print(i)
          print("-" * 25)
            
        elif menu == 3:
          while True: 
                      
            carrinho_item = str(input('''Digite o código do produto:
                  [1]Ração
                  [2]Areia
                  [3]Coleira                     
                  [4]Banho
                  [5]Tosa                
                  [6]Sair  
                  ''')) 
            
            if carrinho_item.isnumeric():
              carrinho_item=int(carrinho_item)                  

              print("-" * 25)
              if carrinho_item ==1:
                qntdst=str(input("Digite a quantidade: "))
                if qntdst.isnumeric():
                  qntd=int(qntdst)
                  total_item1=["Ração",qntd*precos_produtos[0]]
                  total_item.append(total_item1)
                  print("-" * 25)
                 
                else:
                  print("-" * 25)
                  print("ERRO! Digite um número inteiro válido: ")
                  print("-" * 25) 
                  break                                
                              
              elif carrinho_item ==2:
                qntdst=str(input("Digite a quantidade: "))
                if qntdst.isnumeric():
                  qntd=int(qntdst)
                  total_item2=["Areia",qntd*precos_produtos[1]]
                  total_item.append(total_item2)
                  print("-" * 25)
                
                else:
                  print("-" * 25)
                  print("ERRO! Digite um número inteiro válido: ")
                  print("-" * 25) 
                
              elif carrinho_item ==3:
                qntdst=str(input("Digite a quantidade: "))
                if qntdst.isnumeric():
                  qntd=int(qntdst)
                  total_item3=["Coleira",qntd*precos_produtos[2]]
                  total_item.append(total_item3)
                  print("-" * 25)
                  
                else:
                  print("-" * 25)
                  print("ERRO! Digite um número inteiro válido: ")
                  print("-" * 25)        
                            
              elif carrinho_item ==4:
                qntdst=str(input("Digite a quantidade: "))
                if qntdst.isnumeric():
                  qntd=int(qntdst)
                  total_item4=["Banho",qntd*precos_servicos[0]]
                  total_item.append(total_item4)
                  print("-" * 25)
                  
                else:
                  print("-" * 25)
                  print("ERRO! Digite um número inteiro válido: ")
                  print("-" * 25) 

              elif carrinho_item ==5:
                qntdst=str(input("Digite a quantidade: "))
                if qntdst.isnumeric():
                  qntd=int(qntdst)
                  total_item5=["Tosa",qntd*precos_servicos[1]]
                  total_item.append(total_item5)
                  print("-" * 25)
                  
                else:
                  print("-" * 25)
                  print("ERRO! Digite um número inteiro válido: ")
                  print("-" * 25) 

              else:
                break
                
            else:
              print("-" * 25)
              print("ERRO! Digite um número inteiro válido: ")
              print("-" * 25) 
          
      
        elif menu == 4:
          while True:
              print("-" * 25)
              print(f'Carrinho: \n')
        
              soma = 0
              for i in total_item:
                for j in i:
                  if j == i[1]:
                    soma+= j
          
              totalT = soma
              for i in total_item:    
                print(f"{i[0]} R${i[1]} ")          
              print(f"\nTotal = {totalT}")
              print("-" * 25)

              carrinho_item_st = input('''Digite o código do produto a ser removido:
                  [1]Ração
                  [2]Areia
                  [3]Coleira                     
                  [4]Banho
                  [5]Tosa                
                  [6]Sair                  
                  ''')   
              
              if carrinho_item_st.isnumeric():
                carrinho_item=int(carrinho_item_st)

                print("-" * 25)
                if carrinho_item ==1:
                  for i in total_item:
                    for j in i:
                      if j == i [0]:
                        if i [0] == "Ração":
                          total_item.remove(i)
                          totalT -= i[1]                 
                        
                elif carrinho_item ==2:
                  for i in total_item:
                    for j in i:
                      if j == i [0]:
                        if i [0] == "Areia":
                          total_item.remove(i)
                          totalT -= i[1]                    
                          
                elif carrinho_item ==3:
                  for i in total_item:
                    for j in i:
                      if j == i [0]:
                        if i [0] == "Coleira":
                          total_item.remove(i)
                          totalT -= i[1]                   
                                      
                elif carrinho_item ==4:
                  for i in total_item:
                    for j in i:
                      if j == i [0]:
                        if i [0] == "Banho":
                          total_item.remove(i)
                          totalT -= i[1]                                

                elif carrinho_item ==5:
                  for i in total_item:
                    for j in i:
                      if j == i [0]:
                        if i [0] == "Tosa":
                          total_item.remove(i)
                          totalT -= i[1]
                else:
                  break
                            
              else:
                print("-" * 25)
                print("ERRO! Digite um número inteiro válido: ")
                print("-" * 25)
                                    
        elif menu == 5:
          print("-" * 25)
          print(f'Carrinho: \n')
          
          soma = 0
          for i in total_item:
            for j in i:
              if j == i[1]:
                soma+= j
      
          totalT = soma
        
          for i in total_item:    
            print(f"{i[0]} R${i[1]} ")          
          print(f"\nTotal = {totalT}")
          print("-" * 25)

        elif menu == 6:
          print("-" * 25)
          while True:
            print("Você está comprando: ")           
        
            soma = 0
            for i in total_item:
              for j in i:
                if j == i[1]:
                  soma+= j
        
            totalT = soma
            for i in total_item:    
              print(f"{i[0]} R${i[1]} ")          
            print(f"\nTotal = R$ {totalT}")
            print("-" * 25)  


            pagamento_str=str(input(f'''\nSelecionar opção de pagamento:
                [1]Dinheiro:     
          '''))  
            print("-" * 25)

            if pagamento_str.isnumeric():
              pagamento=int(pagamento_str)

              if pagamento == 1:
                rcedulast = input("Digite o valor da cédula do pagamento: ")
                print("-" * 25)

                if int(rcedulast) < totalT:                
                  print("-" * 25)
                  print("ERRO! Valor insuficiente: ")
                  print("-" * 25)
                  break

                if rcedulast.isnumeric():
                  rcedula=int(rcedulast)

                  troco = rcedula - totalT

                  troco2 = troco % 50
                  troco3 = troco2 % 20
                  troco4 = troco3 % 10
                  troco5 = troco4 % 5
                  troco6 = troco5 % 2
                  troco7 = troco6 % 1
                  cedula_50= troco//50
                  cedula_20= troco2//20
                  cedula_10= troco3//10
                  cedula_5= troco4//5
                  cedula_2= troco5//2
                  cedula_1= troco6//1

                  print(f'O seu troco é R${troco}: ')
                  print(f'{cedula_50} notas de R$50')
                  print(f'{cedula_20} notas de R$20')
                  print(f'{cedula_10} notas de R$10')
                  print(f'{cedula_5} notas de R$5')
                  print(f'{cedula_2} notas de R$2')
                  print(f'{cedula_1} notas de R$1')
                else:
                  print("-" * 25)
                  print("ERRO! Digite um número inteiro válido: ")
                  print("-" * 25)
                  break
            
                while True:
                  confirmacaostr = input('''
                    Você deseja confirmar a compra? 
                    [1] Sim
                    [2] Não
                    [3] Voltar''')
                  if confirmacaostr.isnumeric():
                    confirmacao=int(confirmacaostr)
                  
                    if confirmacao == 1:
                      print("Compra finalizada! Seu cupom será entregue na saída.")
                      compra = 1
                      break
                    elif confirmacao == 2:
                      for i in total_item:
                        print(f'{i[0]} R${i[1]} ')
                      print(f'Total = {totalT}')                
                      desistencia = input("Você tem certeza que deseja cancelar a compra? (S)  ou (N)").upper              

                    if desistencia == 'n':
                      continue
                    elif desistencia == 's':                                                  
                      break
                    
                    elif confirmacao == 3:
                      break
                  else:
                    print("-" * 25)
                    print("ERRO! Digite um número inteiro válido: ")
                  break                                
                break   
              else:
                print("-" * 25)
                print("ERRO! Digite um número inteiro válido: ")
            else:
              print("-" * 25)
              print("ERRO! Digite um número inteiro válido: ")
              print("-" * 25)

        elif menu == 7 :
          break 
      else:
        print("-" * 25)
        print("ERRO! Digite um número inteiro válido: \n")
                
  elif inicio == "F":
    if compra == 1:
      print("\n------------AMIGO FIEL----------------")
      print("----------Endereço:Rua da alegria,N 13 -")
      print("----------Bairro:Bela Vista-------------")
      print("Cnpj: 000.0000.000/0--------------------")
      print("Data:15/02/2022-------------------------")
      print(f'------------CUPOM FISCAL---------------')
      print(f'ITEM   PREÇO --------------------------')
      for i in total_item:
        print(f'{i[0]}  R${i[1]}---------------------')

      print(f'TOTAL = R${totalT}-------------------\n')

      print("Obrigado pela preferência. Volte sempre!")
      break
    
    else:
      total_item.clear()     
      print("Esperamos lhe reencontrar em breve!")
      break